#
# CoDiPack, a Code Differentiation Package
#
# Copyright (C) 2015-2023 Chair for Scientific Computing (SciComp), University of Kaiserslautern-Landau
# Homepage: http://www.scicomp.uni-kl.de
# Contact:  Prof. Nicolas R. Gauger (codi@scicomp.uni-kl.de)
#
# Lead developers: Max Sagebaum, Johannes Blühdorn (SciComp, University of Kaiserslautern-Landau)
#
# This file is part of CoDiPack (http://www.scicomp.uni-kl.de/software/codi).
#
# CoDiPack is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# CoDiPack is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
# You should have received a copy of the GNU
# General Public License along with CoDiPack.
# If not, see <http://www.gnu.org/licenses/>.
#
# For other licensing options please contact us.
#
# Authors:
#  - SciComp, University of Kaiserslautern-Landau:
#    - Max Sagebaum
#    - Johannes Blühdorn
#    - Former members:
#      - Tim Albring
#

# Function for driver generation
define define_codi_driver
#  $(1) DRIVER_NAME
#  $(2) DRIVER_INCLUDE
#  $(3) DRIVER_CLASS
#  $(4) CODI_TYPE
#  $(5) DRIVER_TESTS
#  $(6) ADDITIONAL_COMPILE_FLAGS
#  $(7) ADDITIONAL_LINK_FLAGS
  ALL_DRIVERS := $(ALL_DRIVERS) $(1)
  $(BUILD_DIR)/$(1).runner.o : DRIVER_INC = $(CODI_INCLUDE) -DDRIVER='$(2)' -DDRIVER_NAME=$(3) -DCODI_TYPE='$(4)' -DCODI_TYPE_NAME=$(1) $(6)
  $(BUILD_DIR)/$(1).runner.o : DRIVER_TESTS = $(5)
  $(BUILD_DIR)/$(1).runner.exe : DRIVER_LIB = $(7)
endef

VECTOR_DIM = 5

EH_JACOBI_TAPE_TESTS = $(filter-out TestReset, $(ALL_TESTS))
EH_PRIMAL_TAPE_TESTS = $(filter-out TestPreaccumulation% TestReset TestStatementPushHelper, $(ALL_TESTS))

# driver definitions
# First order drivers
$(eval $(call define_codi_driver,D1_fwd,"drivers/codi/forward1stOrder.hpp",CoDiForward1stOrder,codi::RealForward,$(ALL_TESTS),,))

$(eval $(call define_codi_driver,D1_fwdVec,"drivers/codi/forward1stOrder.hpp",CoDiForward1stOrder,codi::RealForwardVec<$(VECTOR_DIM)>,$(ALL_TESTS),,))

$(eval $(call define_codi_driver,D1_rwsJacLin,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverse,$(ALL_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_rwsJacInd,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseIndex,$(ALL_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_rwsJacIndOmp,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseIndexOpenMP,$(ALL_TESTS),-DREVERSE_TAPE -DCODI_EnableOpenMP -fopenmp, -fopenmp))
$(eval $(call define_codi_driver,D1_rwsPrimLin,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReversePrimal,$(ALL_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_rwsPrimInd,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReversePrimalIndex,$(ALL_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_rwsPrimLinInterface,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReversePrimal,$(ALL_TESTS),-DREVERSE_TAPE -DCODI_VariableAdjointInterfaceInPrimalTapes,))
$(eval $(call define_codi_driver,D1_rwsPrimIndInterface,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReversePrimalIndex,$(ALL_TESTS),-DREVERSE_TAPE -DCODI_VariableAdjointInterfaceInPrimalTapes,))

$(eval $(call define_codi_driver,D1_rwsJacLinVec,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseVec<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_rwsJacIndVec,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseIndexVec<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_rwsJacIndVecOmp,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseIndexVecOpenMP<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE -DCODI_EnableOpenMP -fopenmp, -fopenmp))
$(eval $(call define_codi_driver,D1_rwsPrimLinVec,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReversePrimalVec<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_rwsPrimIndVec,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReversePrimalIndexVec<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE,))

$(eval $(call define_codi_driver,D1_eh_fwd,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealForward,$(ALL_TESTS),,))

$(eval $(call define_codi_driver,D1_eh_fwdVec,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealForwardVec<$(VECTOR_DIM)>,$(ALL_TESTS),,))

$(eval $(call define_codi_driver,D1_eh_rwsJacLin,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReverse,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_eh_rwsJacInd,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReverseIndex,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_eh_rwsJacIndOmp,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReverseIndexOpenMP,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE -DCODI_EnableOpenMP -fopenmp, -fopenmp))
$(eval $(call define_codi_driver,D1_eh_rwsPrimLin,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReversePrimal,$(EH_PRIMAL_TAPE_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_eh_rwsPrimInd,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReversePrimalIndex,$(EH_PRIMAL_TAPE_TESTS),-DREVERSE_TAPE,))

$(eval $(call define_codi_driver,D1_eh_rwsJacLinVec,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReverseVec<$(VECTOR_DIM)>,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_eh_rwsJacIndVec,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReverseIndexVec<$(VECTOR_DIM)>,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_eh_rwsJacIndVecOmp,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReverseIndexVecOpenMP<$(VECTOR_DIM)>,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE -DCODI_EnableOpenMP -fopenmp, -fopenmp))
$(eval $(call define_codi_driver,D1_eh_rwsPrimLinVec,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReversePrimalVec<$(VECTOR_DIM)>,$(EH_PRIMAL_TAPE_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_eh_rwsPrimIndVec,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReversePrimalIndexVec<$(VECTOR_DIM)>,$(EH_PRIMAL_TAPE_TESTS),-DREVERSE_TAPE,))

$(eval $(call define_codi_driver,D1_rwsJacLinCombined,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverse,$(ALL_TESTS),-DREVERSE_TAPE -DCODI_RemoveDuplicateJacobianArguments,))
$(eval $(call define_codi_driver,D1_rwsJacLinUnchecked,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseUnchecked,$(ALL_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_rwsJacLinCustomVector,"drivers/codi/reverse1stOrderVectorHelper.hpp",CoDiReverse1stOrderVectorHelper,codi::RealReverse,$(ALL_TESTS),-DREVERSE_TAPE,))

$(eval $(call define_codi_driver,D1_rwsJacLinCombinedVec,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseVec<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE -DCODI_CombineJacobianArguments,))
$(eval $(call define_codi_driver,D1_rwsJacLinCustomVectorVec,"drivers/codi/reverse1stOrderVectorHelper.hpp",CoDiReverse1stOrderVectorHelper,codi::RealReverseVec<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE,))

$(eval $(call define_codi_driver,D1_fwdPrimInd,"drivers/codi/forwardTape1stOrder.hpp",CoDiForwardTape1stOrder,codi::RealReversePrimalIndex,$(EH_PRIMAL_TAPE_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D1_fwdPrimIndVec,"drivers/codi/forwardTape1stOrder.hpp",CoDiForwardTape1stOrder,codi::RealReversePrimalIndexVec<$(VECTOR_DIM)>,$(EH_PRIMAL_TAPE_TESTS),-DREVERSE_TAPE,))

$(eval $(call define_codi_driver,D1_fwdOFwd,"drivers/codi/forward1stOrder.hpp",CoDiForward1stOrder,codi::RealForwardGen<codi::RealForward>,$(ALL_TESTS),-DSECOND_ORDER,))
$(eval $(call define_codi_driver,D1_rwsOFwd,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseGen<codi::RealForward>,$(ALL_TESTS),-DSECOND_ORDER,))

$(eval $(call define_codi_driver,D1_eh_fwdOFwd,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealForwardGen<codi::RealForward>,$(ALL_TESTS),-DSECOND_ORDER,))
$(eval $(call define_codi_driver,D1_eh_rwsOFwd,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReverseGen<codi::RealForward>,$(EH_JACOBI_TAPE_TESTS),-DSECOND_ORDER,))

# Primal drivers
$(eval $(call define_codi_driver,D0_fwd,"drivers/codi/run0thOrder.hpp",CoDi0thOrder,codi::RealForward,$(ALL_TESTS),,))
$(eval $(call define_codi_driver,D0_rwsJacLin,"drivers/codi/run0thOrder.hpp",CoDi0thOrder,codi::RealReverse,$(ALL_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D0_rwsJacInd,"drivers/codi/run0thOrder.hpp",CoDi0thOrder,codi::RealReverseIndex,$(ALL_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D0_rwsJacIndOmp,"drivers/codi/run0thOrder.hpp",CoDi0thOrder,codi::RealReverseIndexOpenMP,$(ALL_TESTS),-DREVERSE_TAPE -DCODI_EnableOpenMP -fopenmp, -fopenmp))
$(eval $(call define_codi_driver,D0_rwsPrimLin,"drivers/codi/run0thOrder.hpp",CoDi0thOrder,codi::RealReversePrimal,$(ALL_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D0_rwsPrimInd,"drivers/codi/run0thOrder.hpp",CoDi0thOrder,codi::RealReversePrimalIndex,$(ALL_TESTS),-DREVERSE_TAPE,))

$(eval $(call define_codi_driver,D0_eh_fwd,"drivers/codi/evalHelper0thOrder.hpp",CoDiEvalHelper0thOrder,codi::RealForward,$(ALL_TESTS),,))
$(eval $(call define_codi_driver,D0_eh_rwsJacLin,"drivers/codi/evalHelper0thOrder.hpp",CoDiEvalHelper0thOrder,codi::RealReverse,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D0_eh_rwsJacInd,"drivers/codi/evalHelper0thOrder.hpp",CoDiEvalHelper0thOrder,codi::RealReverseIndex,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D0_eh_rwsJacIndOmp,"drivers/codi/evalHelper0thOrder.hpp",CoDiEvalHelper0thOrder,codi::RealReverseIndexOpenMP,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE -DCODI_EnableOpenMP -fopenmp, -fopenmp))
$(eval $(call define_codi_driver,D0_eh_rwsPrimLin,"drivers/codi/evalHelper0thOrder.hpp",CoDiEvalHelper0thOrder,codi::RealReversePrimal,$(EH_PRIMAL_TAPE_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D0_eh_rwsPrimInd,"drivers/codi/evalHelper0thOrder.hpp",CoDiEvalHelper0thOrder,codi::RealReversePrimalIndex,$(EH_PRIMAL_TAPE_TESTS),-DREVERSE_TAPE,))
$(eval $(call define_codi_driver,D0_eh_rwsPrim2nd,"drivers/codi/evalHelper0thOrder.hpp",CoDiEvalHelper0thOrder,codi::HessianComputationType,$(ALL_TESTS),,))

# second order drivers
VECTOR_ARG = codi::RealForwardVec<$(VECTOR_DIM)>,codi::Direction<codi::RealForwardVec<$(VECTOR_DIM)>,$(VECTOR_DIM)>

$(eval $(call define_codi_driver,D2_eh_fwd,"drivers/codi/evalHelper2ndOrder.hpp",CoDiEvalHelper2ndOrder,codi::RealForwardGen<codi::RealForward>,$(ALL_TESTS),-DSECOND_ORDER,))

$(eval $(call define_codi_driver,D2_eh_fwdVec,"drivers/codi/evalHelper2ndOrder.hpp",CoDiEvalHelper2ndOrder,codi::RealForwardGen<$(VECTOR_ARG)>,$(ALL_TESTS),-DSECOND_ORDER,))

$(eval $(call define_codi_driver,D2_eh_rwsJacLin,"drivers/codi/evalHelper2ndOrder.hpp",CoDiEvalHelper2ndOrder,codi::RealReverseGen<codi::RealForward>,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE -DSECOND_ORDER,))
$(eval $(call define_codi_driver,D2_eh_rwsJacInd,"drivers/codi/evalHelper2ndOrder.hpp",CoDiEvalHelper2ndOrder,codi::RealReverseIndexGen<codi::RealForward>,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE -DSECOND_ORDER,))
$(eval $(call define_codi_driver,D2_eh_rwsJacIndOmp,"drivers/codi/evalHelper2ndOrder.hpp",CoDiEvalHelper2ndOrder,codi::RealReverseIndexOpenMPGen<codi::RealForward>,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE -DSECOND_ORDER -DCODI_EnableOpenMP -fopenmp, -fopenmp))
$(eval $(call define_codi_driver,D2_eh_rwsPrimLin,"drivers/codi/evalHelper2ndOrder.hpp",CoDiEvalHelper2ndOrder,codi::RealReversePrimalGen<codi::RealForward>,$(EH_PRIMAL_TAPE_TESTS),-DREVERSE_TAPE -DSECOND_ORDER,))
$(eval $(call define_codi_driver,D2_eh_rwsPrimInd,"drivers/codi/evalHelper2ndOrder.hpp",CoDiEvalHelper2ndOrder,codi::RealReversePrimalIndexGen<codi::RealForward>,$(EH_PRIMAL_TAPE_TESTS),-DREVERSE_TAPE -DSECOND_ORDER,))

$(eval $(call define_codi_driver,D2_eh_rwsJacLinVec,"drivers/codi/evalHelper2ndOrder.hpp",CoDiEvalHelper2ndOrder,codi::RealReverseGen<$(VECTOR_ARG)>,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE -DSECOND_ORDER,))
$(eval $(call define_codi_driver,D2_eh_rwsJacIndVec,"drivers/codi/evalHelper2ndOrder.hpp",CoDiEvalHelper2ndOrder,codi::RealReverseIndexGen<$(VECTOR_ARG)>,$(EH_JACOBI_TAPE_TESTS),-DREVERSE_TAPE -DSECOND_ORDER,))
$(eval $(call define_codi_driver,D2_eh_rwsPrimLinVec,"drivers/codi/evalHelper2ndOrder.hpp",CoDiEvalHelper2ndOrder,codi::RealReversePrimalGen<$(VECTOR_ARG)>,$(EH_PRIMAL_TAPE_TESTS),-DREVERSE_TAPE -DSECOND_ORDER,))
$(eval $(call define_codi_driver,D2_eh_rwsPrimIndVec,"drivers/codi/evalHelper2ndOrder.hpp",CoDiEvalHelper2ndOrder,codi::RealReversePrimalIndexGen<$(VECTOR_ARG)>,$(EH_PRIMAL_TAPE_TESTS),-DREVERSE_TAPE -DSECOND_ORDER,))
