default:
  image: fedora:41
  timeout: 2h
  tags:
    - docker

variables:
  COMMON_PACKAGES: "diffutils binutils git"

codi-general:
  script:
    - dnf install -y $COMMON_PACKAGES g++
    - cd tests/general
    - make all

codi-events:
  script:
    - dnf install -y $COMMON_PACKAGES g++
    - cd tests/events
    - make all

codi-functional:
  script:
    - dnf install -y $COMMON_PACKAGES g++
    - cd tests/functional
    - make all

codi-examples:
  script:
    - dnf install -y $COMMON_PACKAGES g++
    - make examples

opdi:
  script:
    - dnf install -y $COMMON_PACKAGES g++
    - git clone --depth 1 --branch develop https://github.com/SciCompKL/OpDiLib.git
    - export CODI_DIR=$(pwd)/include
    - cd OpDiLib
    - export OPDI_DIR=$(pwd)/include
    - cd tests
    - export CXX=g++
    - make all

medi:
  image: ubuntu:24.04
  script:
    - apt update && apt install -y $COMMON_PACKAGES build-essential openmpi-bin libopenmpi-dev
    - git clone --depth 1 --branch develop https://github.com/SciCompKL/MeDiPack.git
    - export CODI_DIR=$(pwd)
    - cd MeDiPack/tests
    - export OMPI_ALLOW_RUN_AS_ROOT=1
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    - make all
