
# Function for driver generation
define define_codi_driver
#  $(1) DRIVER_NAME
#  $(2) DRIVER_INCLUDE
#  $(3) DRIVER_CLASS
#  $(4) CODI_TYPE
#  $(5) DRIVER_TESTS
#  $(6) ADDITIONAL_FLAGS
  ALL_DRIVERS := $(ALL_DRIVERS) $(1)
  $(BUILD_DIR)/$(1).runner.o : DRIVER_INC = -I$(CODI_DIR)/include -DDRIVER='$(2)' -DDRIVER_NAME=$(3) -DCODI_TYPE='$(4)' -DCODI_TYPE_NAME=$(1) $(6)
  $(BUILD_DIR)/$(1).runner.o : DRIVER_TESTS = $(5)
endef

VECTOR_DIM = 5

EH_TESTS = $(filter-out TestPreaccumulation% TestReset TestStatementPushHelper, $(ALL_TESTS))

# driver definitions
# First order drivers
$(eval $(call define_codi_driver,D1_fwd,"drivers/codi/forward1stOrder.hpp",CoDiForward1stOrder,codi::RealForward,$(ALL_TESTS),))

$(eval $(call define_codi_driver,D1_fwdVec,"drivers/codi/forward1stOrder.hpp",CoDiForward1stOrder,codi::RealForwardVec<$(VECTOR_DIM)>,$(ALL_TESTS),))

$(eval $(call define_codi_driver,D1_rwsJacLin,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverse,$(ALL_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_rwsJacInd,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseIndex,$(ALL_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_rwsPrimLin,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReversePrimal,$(ALL_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_rwsPrimInd,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReversePrimalIndex,$(ALL_TESTS),-DREVERSE_TAPE))

$(eval $(call define_codi_driver,D1_rwsJacLinVec,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseVec<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_rwsJacIndVec,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseIndexVec<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_rwsPrimLinVec,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReversePrimalVec<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_rwsPrimIndVec,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReversePrimalIndexVec<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE))

$(eval $(call define_codi_driver,D1_eh_fwd,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealForward,$(EH_TESTS),))

$(eval $(call define_codi_driver,D1_eh_fwdVec,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealForwardVec<$(VECTOR_DIM)>,$(EH_TESTS),))

$(eval $(call define_codi_driver,D1_eh_rwsJacLin,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReverse,$(EH_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_eh_rwsJacInd,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReverseIndex,$(EH_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_eh_rwsPrimLin,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReversePrimal,$(EH_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_eh_rwsPrimInd,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReversePrimalIndex,$(EH_TESTS),-DREVERSE_TAPE))

$(eval $(call define_codi_driver,D1_eh_rwsJacLinVec,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReverseVec<$(VECTOR_DIM)>,$(EH_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_eh_rwsJacIndVec,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReverseIndexVec<$(VECTOR_DIM)>,$(EH_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_eh_rwsPrimLinVec,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReversePrimalVec<$(VECTOR_DIM)>,$(EH_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_eh_rwsPrimIndVec,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReversePrimalIndexVec<$(VECTOR_DIM)>,$(EH_TESTS),-DREVERSE_TAPE))

$(eval $(call define_codi_driver,D1_rwsJacLinCombined,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverse,$(ALL_TESTS),-DREVERSE_TAPE -DCODI_RemoveDuplicateJacobianArguments))
$(eval $(call define_codi_driver,D1_rwsJacLinUnchecked,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseUnchecked,$(ALL_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D1_rwsJacLinCustomVector,"drivers/codi/reverse1stOrderVectorHelper.hpp",CoDiReverse1stOrderVectorHelper,codi::RealReverse,$(ALL_TESTS),-DREVERSE_TAPE))

$(eval $(call define_codi_driver,D1_rwsJacLinCombinedVec,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseVec<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE -DCODI_CombineJacobianArguments))
$(eval $(call define_codi_driver,D1_rwsJacLinCustomVectorVec,"drivers/codi/reverse1stOrderVectorHelper.hpp",CoDiReverse1stOrderVectorHelper,codi::RealReverseVec<$(VECTOR_DIM)>,$(ALL_TESTS),-DREVERSE_TAPE))

$(eval $(call define_codi_driver,D1_fwdOFwd,"drivers/codi/forward1stOrder.hpp",CoDiForward1stOrder,codi::RealForwardGen<codi::RealForward>,$(ALL_TESTS),-DSECOND_ORDER))
$(eval $(call define_codi_driver,D1_rwsOFwd,"drivers/codi/reverse1stOrder.hpp",CoDiReverse1stOrder,codi::RealReverseGen<codi::RealForward>,$(ALL_TESTS),-DSECOND_ORDER))

$(eval $(call define_codi_driver,D1_eh_fwdOFwd,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealForwardGen<codi::RealForward>,$(EH_TESTS),-DSECOND_ORDER))
$(eval $(call define_codi_driver,D1_eh_rwsOFwd,"drivers/codi/evalHelper1stOrder.hpp",CoDiEvalHelper1stOrder,codi::RealReverseGen<codi::RealForward>,$(EH_TESTS),-DSECOND_ORDER))

# Primal drivers
$(eval $(call define_codi_driver,D0_fwd,"drivers/codi/run0thOrder.hpp",CoDi0thOrder,codi::RealForward,$(ALL_TESTS),))
$(eval $(call define_codi_driver,D0_rwsJacLin,"drivers/codi/run0thOrder.hpp",CoDi0thOrder,codi::RealReverse,$(ALL_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D0_rwsJacInd,"drivers/codi/run0thOrder.hpp",CoDi0thOrder,codi::RealReverseIndex,$(ALL_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D0_rwsPrimLin,"drivers/codi/run0thOrder.hpp",CoDi0thOrder,codi::RealReversePrimal,$(ALL_TESTS),-DREVERSE_TAPE))
$(eval $(call define_codi_driver,D0_rwsPrimInd,"drivers/codi/run0thOrder.hpp",CoDi0thOrder,codi::RealReversePrimalIndex,$(ALL_TESTS),-DREVERSE_TAPE))
