# All tests in this files are first order derivatives
DRIVER_MODE := primal

# Complete list of primal test files
TESTS_PRIMAL := $(patsubst $(TEST_DIR)/%.cpp,$(RESULT_DIR)/$(DRIVER_MODE)/%.test,$(TEST_FILES))

# The first 3 lines of each driver define the basic parameters for this driver.
# DRIVER_NAME:    The short name for the driver. This used to create the specific files for the driver
# DRIVER_TESTS:   The full list of tests which are run for this driver. See the general test list for details.
# DRIVER:         The special flags for this driver. It needs to be defined inside the build rule.
# The eval line creates the rules and dependencies for the driver

# Driver for RealForwardVector
DRIVER_NAME  := D0_double
DRIVER_TESTS := $(BASIC_TESTS) $(REVERSE_TESTS) $(REVERSE_VALUE_TESTS)
DRIVER_SRC = $(DRIVER_DIR)/forwardCoDi/forwardDriverPrimal.cpp
$(BUILD_DIR)/$(DRIVER_MODE)/%_$(DRIVER_NAME).exe : DRIVER_INC = $(CODI_INCLUDE) -I$(DRIVER_DIR)/forwardCoDi -DDOUBLE
$(eval $(value DRIVER_INST))

# Driver for RealForward
DRIVER_NAME  := D0_FWD
DRIVER_TESTS := $(BASIC_TESTS) $(REVERSE_TESTS) $(REVERSE_VALUE_TESTS)
DRIVER_SRC = $(DRIVER_DIR)/forwardCoDi/forwardDriverPrimal.cpp
$(BUILD_DIR)/$(DRIVER_MODE)/%_$(DRIVER_NAME).exe : DRIVER_INC = $(CODI_INCLUDE) -I$(DRIVER_DIR)/forwardCoDi -DFWD
$(eval $(value DRIVER_INST))
